---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: websocket-app-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: websocket-app
  targetNamespace: websocket-app-staging
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: staging-websocket-server
    namespace: websocket-app-staging
  timeout: 2m0s
  wait: true
