---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: websocket-app-dev
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: websocket-app
  targetNamespace: websocket-app-dev
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: dev-websocket-server
    namespace: websocket-app-dev
  timeout: 2m0s
  wait: true
