apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-server
  annotations:
    # Development - shorter timeouts for faster feedback
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - http:
      paths:
      - path: /wsapp
        pathType: Prefix
        backend:
          service:
            name: websocket-server
            port:
              number: 8080
