apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: websocket-app-dev

namePrefix: dev-

commonLabels:
  environment: dev

bases:
- ../../base

patches:
- path: replica-patch.yaml
- path: resource-patch.yaml
- path: image-patch.yaml

configMapGenerator:
- name: websocket-config
  literals:
  - RUST_LOG=debug
  - ENVIRONMENT=development
