apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: websocket-app-staging

namePrefix: staging-

commonLabels:
  environment: staging

bases:
- ../../base

patches:
- path: replica-patch.yaml
- path: image-patch.yaml

configMapGenerator:
- name: websocket-config
  literals:
  - RUST_LOG=info
  - ENVIRONMENT=staging
